### ISSUE TITLE
The requested PHP extension ext-intl * is missing from your system

### ISSUE THREAD

**Issue by andreisusanu** [nathanheffley/laravel-phpunit-action#2]
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-intl * is missing from your system. Install or enable PHP's intl extension.
  Problem 2
    - Installation request for laravel/nova v3.3.0 -> satisfiable by laravel/nova[v3.3.0].
    - laravel/nova v3.3.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php-cli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Warning: require(/github/workspace/vendor/autoload.php): failed to open stream: No such file or directory in /github/workspace/artisan on line 18

Fatal error: require(): Failed opening required '/github/workspace/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /github/workspace/artisan on line 18
Could not open input file: vendor/bin/phpunit
```

**Comment by nathanheffley** [comment]
This action doesn't install things to your system, it assumes you have actions setting up a system that is able to run things like PHPUnit.

Did you use the configuration in the README.md to run this on `ubuntu-latest`?

**Comment by andreisusanu** [comment]
Hi. I am running this on ubuntu-latest. Here is my job definition:

```
jobs:
  phpunit:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure composer auth for Laravel Nova
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_API_KEY }}
      - uses: nathanheffley/laravel-phpunit-action@master
```

So it looks like ubuntu-latest is missing php-intl :(
